### ISSUE TITLE
Background windows command line

### ISSUE THREAD

**Issue by nesteam** [refractionPOINT/limacharlie#39]
Hi,

I'm really interested in your project !

I'm currently searching a way to execute the windows exe in background so you don't have always a console window dispolayed on you desktop. Indeed, I would like to deploy the exe via a GPO.

Is this possible ? Do you have any clues to perform this ?

Thank you in advance for your time !

Best regards,
![2016-08-16 11_09_19-](https://cloud.githubusercontent.com/assets/21055795/17693972/ec2f38e6-63a1-11e6-8b79-6f5d617c8021.png)

**Comment by seanthegeek** [comment]
Give this a try
   
    C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NoLogo -NonInteractive hcp_win_x64_release_0.10.exe

**Comment by maximelb** [comment]
Good idea. The other thing you can do if you don't mind actually having it installed as a service (vs running the executable itself every time) is to install it as a service.

To do this just schedule the executable through your gpo to run once on the computers but this time run it with the "-i" argument on the command line. This will install it as a service and start it. Once that is done you don't have to keep running the exe through a gpo since it will start at boot automatically from the installed service.

**Comment by nesteam** [comment]
Hi,

Thank you for your reply :)

Could you be more specific about service installation via GPO ? 

I have created a .bat file wtih this command : 
"\\@IPserver\Shared\SOC\hcp_win_x64_release_0.10.ex /VERYSILENT /SPPRESSMSGBOXES /NORESTART /NOICONS"

This .bat file is working when launched directly by users but not via GPO. It's stored on a shared folder so when you want to launch it, you have to confirm an "alert box" from Windows.

Thanks in advance for your help !

Best regards.

**Comment by maximelb** [comment]
I think what you'll want to do is have your batch file do:

"\@IPserver\Shared\SOC\hcp_win_x64_release_0.10.ex -i"

This will install LC on the box as a service. (You can run -r instead later if you want to uninstall).
Note that a command prompt will pop up for a split second as it installs, but it won't stay up. I'm not really familiar with making a batch file not pop up at all so if it's critical to never even see it for a split second I can help you have a look to find a solution. Let me know.
